casots/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls'))
]
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url


app_name='courses'

urlpatterns = [
     
    # path('',views.home, name='home'),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('registration/',views.register, name='registration'),
#     path('login/', views.login_view, name='login'),
    
    #new
    path('loginquiz/<slug:quiz>/', views.login_quiz, name='login_quiz'),

    path('logout/',views.logout_view, name='logout'),   
    path('courses/', views.courses_list, name='course_list' ),
    path('category/<slug:category_slug>/', views.courses_list, name='category_list_by_category'),
    path('contact-us/' ,views.contact_us, name='contact_us'),

 
    path('courses/<slug:course_slug>/',views.course_summary, name = 'course_summary'),
    
    
    # reset password
    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name='courses/registration/password_reset.html'),
         name='reset_password'),
    
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='courses/registration/password_reset_sent.html'),
         name='password_reset_done'),
    
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='courses/registration/password_reset_form.html'),
         name='password_reset_confirm'),
    
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='courses/registration/password_reset_done.html'),
         name='password_reset_complete'),
    
    
     # QUIZ SECTION
    path('quizinstructions/<str:category>/', views.quiz_instructions, name='quiz_instructions'),
 
     #trial
     path('quiz/<str:quiz>/',views.index, name='index'),

     path('quiz_performance/', views.quiz_performance, name='quiz_performance'),

      # Leadership board. For all test takers
    path('leaderboard/<str:quiz>/', views.leadership_board, name='leadership_board'),


#     path('course/<str:category>/', views.course_main, name='course_main'),
    
     
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/list.css' %}">
    <link rel="stylesheet" href="{% static 'css/description.css' %}">
    <link rel="stylesheet" href="{% static 'css/about.css' %}">
    <link rel="stylesheet" href="{% static 'css/sign_in.css' %}">
    <link rel="stylesheet" href="{% static 'css/contact-us.css' %}">
    <link href="https://vjs.zencdn.net/7.8.4/video-js.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://codepen.io/heff/pen/EarCt">
  <script src="https://vjs.zencdn.net/ie8/1.1.2/videojs-ie8.min.js"></script>
 

    <title>Document</title>
</head>
<body>
  <!-- header -->
    <header>
        <nav class="navbar  navbar-expand-lg fixed-top" style="background-color:black">
            <div class="container">
            <a class="navbar-brand" href="{% url 'courses:home' %}"><span class="unique1">Cas</span><span class="white">ots</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item active mr-2">
                  <a class="nav-link" href="{% url 'courses:home' %}">Home</a>
                </li>
                <li class="nav-item dropdown mr-2">
                  <a class="nav-link" href="{% url 'courses:course_list' %}" >
                    Courses 
                    <!-- id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" -->
                    <!-- <i class="fa fa-angle-down down" aria-hidden="true"></i> -->
                  </a>
                  <!-- <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div> -->
                </li>
                <li class="nav-item mr-2">
                  <a class="nav-link" href="{% url 'courses:contact_us' %}">Contact</a>
                </li>
                <li class="nav-item mr-2">
                    <a class="nav-link" href="{% url 'courses:about' %}">About us</a>
                  </li>
                <!-- <li class="nav-item mr-2">
                <a class="nav-link" href="#"><i class="fa fa-search" aria-hidden="true"></i></a>
                </li>
                <li class="nav-item mr-2">
                    <a class="nav-link" href="#"><i class="fa fa-user" aria-hidden="true"></i></a>
                </li> -->
              </ul>
            </div>
          </div>    
        </nav>
    </header>
 <!-- ending header -->
    
    {% block content %}
        
    {% endblock content %}
        
<!-- footer -->

<footer class="footer-credit pb-5">
  <div class="container d-flex  flex-wrap justify-content-between" >
    
    <div class="quick-links mt-4 ">
      <h3 class="footer-heading">Quick Links</h3>
      <div class="links flex-column d-flex mt-3">
        <a href="{% url 'courses:home' %}" class="footer-links">Home</a>
        <a href="{% url 'courses:course_list' %}" class="footer-links">Courses</a>
        <a href="" class="footer-links">Contact</a>
        <a href="{% url 'courses:about' %}" class="footer-links">About</a>
      </div>
    </div>

    <div class="resourcs mt-4">
      <h3 class="footer-heading">Resources</h3>
      <div class="links flex-column d-flex mt-3">
        <a href="" class="footer-links">Guides</a>
        <a href="" class="footer-links">Research</a>
        <a href="" class="footer-links">Experts</a>
        <a href="" class="footer-links">Agencies</a>
      </div>
    </div>

    <div class="newsletter mt-4">
      <h3 class="footer-heading">Newsletter</h3>
      <span>you can try us</span>
      <div class="mt-3 ">
        <form action="">
          <div class="try-us d-flex">
            <input type="text" class='try-us-input' placeholder="your email address">
              <a href="" class="btn btn-submit submit-link">
              <i class="fas fa-paper-plane "></i>
            </a>
          </div>
        </form>
      </div>
    </div>

    <div class="social-icons mt-4">
      <div class="links row mt-3">
        <a href=""><div class="icon col-md-6"><i class="fab fa-facebook-f footer-icon " aria-hidden="true"></i></div></a>
        <a href=""><div class="icon col-md-6"><i class="fab fa-twitter footer-icon " aria-hidden="true"></i></div></a>
        <a href=""><div class="icon"><i class="fas fa-baseball-ball footer-icon "></i></div></a>
        <a href=""><div class="icon"><i class="fab fa-linkedin-in footer-icon " aria-hidden="true"></i></div></a>
      </div>
    </div>
  </div>
</footer>

<!-- ending footer -->
  
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
</script>
<script src='asset/js/sticky.js'></script>
</body>

</html>