casots/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls'))
]
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url


app_name='courses'

urlpatterns = [
     
    # path('',views.home, name='home'),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('registration/',views.register, name='registration'),
#     path('login/', views.login_view, name='login'),
    
    #new
    path('loginquiz/<slug:quiz>/', views.login_quiz, name='login_quiz'),

    path('logout/',views.logout_view, name='logout'),   
    path('courses/', views.courses_list, name='course_list' ),
    path('category/<slug:category_slug>/', views.courses_list, name='category_list_by_category'),
    path('contact-us/' ,views.contact_us, name='contact_us'),

 
    path('courses/<slug:course_slug>/',views.course_summary, name = 'course_summary'),
    
    
    # reset password
    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name='courses/registration/password_reset.html'),
         name='reset_password'),
    
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='courses/registration/password_reset_sent.html'),
         name='password_reset_done'),
    
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='courses/registration/password_reset_form.html'),
         name='password_reset_confirm'),
    
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='courses/registration/password_reset_done.html'),
         name='password_reset_complete'),
    
    
     # QUIZ SECTION
    path('quizinstructions/<str:category>/', views.quiz_instructions, name='quiz_instructions'),
 
     #trial
     path('quiz/<str:quiz>/',views.index, name='index'),

     path('quiz_performance/', views.quiz_performance, name='quiz_performance'),

      # Leadership board. For all test takers
    path('leaderboard/<str:quiz>/', views.leadership_board, name='leadership_board'),


#     path('course/<str:category>/', views.course_main, name='course_main'),
    
     
]

templates/quizTest/error.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset='UTF-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <title>Home</title>
        <style>
            *{
                margin: 0px;
            }
            body{
                font-family: Arial, Helvetica, sans-serif;
                display: flex;
                flex-wrap: wrap;
            }
            a{
                text-decoration: none;
                color: rgb(48, 44, 44);
                font-size: large;
            
            }
            

            #categories{
                display: flex;
                flex-wrap: wrap;
                width: 60%;
                max-height: 400px;
            }

            .category{
                border: 2px solid rgb(223, 221, 221);
                margin: 10px;
                justify-content: center;
                align-items: center;
                width: 45%;
                border-radius: 10px;
                background-color: white;
                cursor: pointer;
                
            }


            #quiz_instruction{
                background-color: navy;
                color: aliceblue;
            }
            .category_name{
                padding-top: 18px;
                padding-bottom: 18px;
                border-top: 1px solid rgb(232, 228, 228);
                justify-content: center;
                margin: auto;
                
                text-align: center;
                
                border-bottom-left-radius: 10px;
                border-bottom-right-radius: 10px;
            }

            .category_image{
                width: 100%;
                display: block;
                margin: auto;
                margin-bottom: 0px;
                justify-content: center;
                border-top-left-radius: 10px;
                border-top-right-radius: 10px;
                
            }
            .category_image img{
                width: 100%;
                border-top-left-radius: 10px;
                border-top-right-radius: 10px;
            }
            #toQuiz{
                border: 1px solid rgb(166, 166, 216);
                border-radius: 5px;
                background-color: rgb(0, 0, 70);
                padding: 5px;
                
            }
            #toQuiz a{
                color: aliceblue;
            }
            

            @media (max-width: 800px){
                body{
                    background-color: white;
                }
                .category_image{
                width: 100%;
                }
                .category_name{
                    width: 100%;
                }

                .category{
                    
                    width: 99%;
                    margin-bottom: 10px;
                   
                }
                #categories{
                    width: 100%;
                }
               
            }
        </style>
        <!-- Styling for the quiz navigation-->
        <link rel='stylesheet' href='{% static "quizTest/quiz_nav.css" %}'>

        <!--JavaScript to make navigation more responsible-->
        <script src='{% static "quizTest/quiz_nav.js" %}'></script>
    </head>

    <body>

        <!--Include the navigation points and their url references here-->
        <nav id='nav'>
            <p class='nav_home'>Dashboard  </p>
            <div id='nav_house'>
                <div>
                    <h4>Header 1</h4>
                    <br>
                    <a href='#'><p>Exams</p></a>
                    <p><a href='{% url "courses:home" %}'>Home</a></p>
                    
                </div> 

                <div>
                    <h4>Header 2</h4>
                    <br>
                    <p><a href='#'>casos Link 3</a></p>
                    <p><a href='#'>casots Link 4</a></p>
                    <p><a href='#'>casots Link 5</a></p>
                    <p><a href='#'>casots Link 6</a></p>
                </div> 

                <div>
                    <h4>Header 3</h4>
                    <br>
                    <p><a href='#'>casots Link 7</a></p>
                    
                </div> 
            </div>
        </nav>
        <div id='categories'>
        
            
               
                    <div class='category' id='quiz_instruction'>
                          
                            <div class='category_name'>
                                    {% if error_msg %}
                                        <h3>{{ error_msg }} </h3>
                                   {% else %}
                                       <h2>Nothing here yet</h2>
                                   {% endif %}

                                   {% if extra_info %}
                                     <h3>  {{ extra_info }} </h3> 
                                    {% endif %}
                            </div>
                            
                        
                    </div>
               
            
        

       
      </div>
    </body>
</html>

templates/quizTest/quiz_details.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset='UTF-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <title>Home</title>
        <style>
            *{
                margin: 0px;
            }
            body{
                font-family: Arial, Helvetica, sans-serif;
                display: flex;
                flex-wrap: wrap;
            }
            a{
                text-decoration: none;
                color: rgb(48, 44, 44);
                font-size: large;
            
            }
            

            #categories{
                display: flex;
                flex-wrap: wrap;
                width: 60%;
                max-height: 400px;
            }

            .category{
                border: 2px solid rgb(223, 221, 221);
                margin: 10px;
                justify-content: center;
                align-items: center;
                width: 45%;
                border-radius: 10px;
                background-color: white;
                cursor: pointer;
                
            }


            #quiz_instruction{
                background-color: navy;
                color: aliceblue;
            }
            .category_name{
                padding-top: 18px;
                padding-bottom: 18px;
                border-top: 1px solid rgb(232, 228, 228);
                justify-content: center;
                margin: auto;
                
                text-align: center;
                
                border-bottom-left-radius: 10px;
                border-bottom-right-radius: 10px;
            }

            .category_image{
                width: 100%;
                display: block;
                margin: auto;
                margin-bottom: 0px;
                justify-content: center;
                border-top-left-radius: 10px;
                border-top-right-radius: 10px;
                
            }
            .category_image img{
                width: 100%;
                border-top-left-radius: 10px;
                border-top-right-radius: 10px;
            }
            #toQuiz{
                border: 1px solid rgb(166, 166, 216);
                border-radius: 5px;
                background-color: rgb(0, 0, 70);
                padding: 5px;
                color: aliceblue;
                margin: auto;
                
            }
            

            @media (max-width: 800px){
                body{
                    background-color: white;
                }
                .category_image{
                width: 100%;
                }
                .category_name{
                    width: 100%;
                }

                .category{
                    
                    width: 99%;
                    margin-bottom: 10px;
                   
                }
                #categories{
                    width: 100%;
                }
               
            }
        </style>
        <!-- Styling for the quiz navigation-->
        <link rel='stylesheet' href='{% static "quizTest/quiz_nav.css" %}'>

        <!--JavaScript to make navigation more responsible-->
        <script src='{% static "quizTest/quiz_nav.js" %}'></script>
    </head>

    <body>

        <!--Include the navigation points and their url references here-->
        <nav id='nav'>
            <p class='nav_home'>Dashboard  </p>
            <div id='nav_house'>
                <div>
                    <h4>Header 1</h4>
                    <br>
                    <a href='#'><p>Exams</p></a>
                    <p><a href='{% url "courses:home" %}'>Home</a></p>
                    <p  class='active'>{% if quizName %}{{ quizName.0.course.name }} Materials{% endif %}</p>
                </div> 

                <div>
                    <h4>Header 2</h4>
                    <br>
                    <p><a href='#'>casos Link 3</a></p>
                    <p><a href='#'>casots Link 4</a></p>
                    <p><a href='#'>casots Link 5</a></p>
                    <p><a href='#'>casots Link 6</a></p>
                </div> 

                <div>
                    <h4>Header 3</h4>
                    <br>
                    <p><a href='#'>casots Link 7</a></p>
                    
                </div> 
            </div>
        </nav>
        <div id='categories'>
        {% if quizName %}
            
                {% for quiz in quizName %}
                    <div class='category' id='quiz_instruction'>
                          
                            <div class='category_name'>
                                <h2>Quiz instructions for {{ quiz.course.name }}</h2>
                                <br>
                                <p>{{ quiz.description }}</p>
                                <br>

                                <p>Quiz duration: {{ quiz.duration }} {{ quiz.time_denotation }}</p>
                                <br>

                                <p>Users have a total of 2 attempts within a period of 6 months for each course</p>

                                <br>
                                
                            </div>
                            <form action='{% url "courses:index" quiz.course.name  %}' method='POST'>
                                {% csrf_token %}
                                
                                <button id='toQuiz'>Click to start</button>
                            </form>
                        
                    </div>
                {% endfor%}
            
        {% else %}
        <div id='category'>
            <h2>Nothing here yet</h2>
        </div>
        {% endif %}

       
      </div>
    </body>
</html>

templates/quizTest/quiz_performance.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <title>Quiz Performance</title>

        <style>
            *{
                margin: 0px;
            }
            body{
                font-family: Helvetica, sans-serif, Arial;
                display: flex;
                flex-wrap: wrap;
            }
            #score_container{
                background-color: white;
                border: 1px solid rgb(239, 236, 236);
                padding: 20px;
                box-shadow: 2px 2px 2px 2px rgb(228, 226, 226);
                display: flex;
                flex-wrap: wrap;
                width: 90%;
                
            }
            #score{
                width: 90%;
                padding-top: 20px;
                padding-bottom: 20px;
                border-radius: 5px;
                background-color: white;
                text-align: center;
                font-size: 2em;
                margin: auto;
                
            }
            

            #user_course{
                width: 100%;
                margin: auto;
                display: flex;
                color: rgb(255, 238, 238);
                flex-wrap: wrap;
                justify-content: center;
                
            }
            #user, #course{
                width: 40%;
                text-align: center;
                margin: 10px;
                padding-top: 10px;
                padding-bottom: 10px;
                border-radius: 8px;

            }
            #user{
                background-color: rgb(0, 96, 0);
            }
            #course{
                background-color: brown;
            }

            /*VERSION 2 ADDITIONS*/

            

            #history{
                border: 1px solid rgb(230, 229, 229);
                border-radius: 12px;
                margin-top: 12px;
                justify-content: center;
                align-items: center;
                padding: 12px;
            }

            .summary{
                display: flex;
                flex-wrap: wrap;
                justify-content: center;
                align-items: center;
                padding-top: 15px;
                padding-bottom: 15px;

                border: 1px solid rgb(240, 237, 237);
                border-radius: 5px;
                margin-top: 5px;
                cursor: pointer;
            }

            .summary .short{
                width: 40%;
                text-align: center;
                font-size: large;
            }
            .main_body{
                width: 101%;
                margin-top: 15px;
                justify-content: center;
            }

            @media (min-width: 799px){
                .main_body{
                    width:60%;
                    margin-left: 10px;
                }
            }

        </style>

        <!-- Styling for the quiz navigation-->
        <link rel='stylesheet' href='{% static "quizTest/quiz_nav.css" %}'>

        <!--JavaScript to make navigation more responsible-->
        <script src='{% static "quizTest/quiz_nav.js" %}'></script>

        <script>
            
            document.addEventListener('DOMContentLoaded', () => {
                //Prevent user from going back once she answers at least one question
                history.pushState(null, null, location.href);
                    window.onpopstate = function () {
                        history.go(1);
                    };

                

                

                
            })
        </script>

    </head>

    <body>
        
         <!--Include the navigation points and their url references here-->
         <nav id='nav'>
            <p class='nav_home'>Dashboard  </p>
            <div id='nav_house'>
                
                <div>
                    <h4>Header 1</h4>
                    <br>
                    <p><a href='{% url "courses:home" %}'>Home</a></p>
                </div> 

                <div>
                    <h4>Header 2</h4>
                    <br>
                    <p><a href='#'>casos Link 3</a></p>
                    <p><a href='#'>casots Link 4</a></p>
                    <p><a href='#'>casots Link 5</a></p>
                    <p><a href='#'>casots Link 6</a></p>
                </div> 

                <div>
                    <h4>Header 3</h4>
                    <br>
                    <p><a href='#'>casots Link 7</a></p>
                    
                </div> 
            </div>
        </nav>

        <br>
        <div class='main_body'>
        <div id='score_container'>

                <div id='dateholder'>
                    {% if submission_date %}
                        {{ submission_date }}
                    {% endif %}
                </div>

                <div id='score'>
                    {% if score %}
                   <p>Your Score: {{ score }}%</p> 
                        
                    {% endif %}
                </div>
            

            <div id='user_course'>
                <div id='user'>
                    {% if user %}
                        {{ user }}
                    {% endif %}
                </div>

                <div id='course'>
                    {% if course %}
                        {{ course }}
                    {% endif %}
                </div>
            

            
        
        </div>

           <br>
        </div>

        <div id='history'>
            <p style='text-align: center;'><strong>History</strong> </p>
            {% if user_performances %}

            {% for performance in user_performances %}
                <div class='summary' data-score='{{ performance.score }}' data-course='{{ performance.course }}' data-date='{{ performance.date }}'>
                    <p class='short'>{{ performance.course }}</p>
                    <p class='short'>{{ performance.date }}</p>
                </div>
            {% endfor %}
            
            {% else %}
                <div class='summary'>
                    <p><strong>No History yet</strong></p>
                </div>
            {% endif %}

        </div>

    </div>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            //What we want to achieve with the javascript is, on click of a previous performance, it replaces the content of the displayed performance
            //Query for all performances
            History = document.querySelectorAll('.summary')
            History.forEach(function(summary){

                //On click of each performance(summary)
                summary.onclick = function(){
                    //Change all other summaries background color to white
                    History.forEach(function(changeColor){
                        changeColor.style.backgroundColor = 'white';
                    })
                    //While you keep the current summary's color at light blue for example
                    this.style.backgroundColor = 'rgb(221, 221, 250)';

                    // This section attempts to replace the displayed performance
                        //Get the data you want to pass in
                        displayScore = this.getAttribute('data-score')
                        displayCourse = this.getAttribute('data-course')
                        displayDate = this.getAttribute('data-date')

                        //Replace the current displayed performance with the new data
                        document.querySelector('#score').innerHTML = `<p>Your Score: ${displayScore}%</p>`
                        document.querySelector('#user_course #course').innerHTML = `${displayCourse}`
                        document.querySelector('#score_container #dateholder').innerHTML = `Date Taken: ${displayDate}`
           


                    
                }
            })
        })
    </script>
    </body>
</html>

templates/quizTest/ranked_performance.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset='utf-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
        <title>Quiz Performance</title>

        <style>
            *{
                margin: 0px;
            }
            body{
                font-family: Helvetica, sans-serif, Arial;
                display: flex;
                flex-wrap: wrap;
            }
            #score_container{
                background-color: white;
                border: 1px solid rgb(239, 236, 236);
                padding: 20px;
                box-shadow: 2px 2px 2px 2px rgb(228, 226, 226);
                display: flex;
                flex-wrap: wrap;
                width: 90%;
                
            }
            #score{
                width: 90%;
                padding-top: 20px;
                padding-bottom: 20px;
                border-radius: 5px;
                background-color: white;
                text-align: center;
                font-size: 2em;
                margin: auto;
                
            }
            

            #user_course{
                width: 100%;
                margin: auto;
                display: flex;
                color: rgb(255, 238, 238);
                flex-wrap: wrap;
                justify-content: center;
                
            }
            #user, #course{
                width: 40%;
                text-align: center;
                margin: 10px;
                padding-top: 10px;
                padding-bottom: 10px;
                border-radius: 8px;

            }
            #user{
                background-color: rgb(0, 96, 0);
            }
            #course{
                background-color: brown;
            }

            /*VERSION 2 ADDITIONS*/

            

            #history{
                border: 1px solid rgb(230, 229, 229);
                border-radius: 12px;
                margin-top: 12px;
                justify-content: center;
                align-items: center;
                padding: 12px;
            }

            .summary{
                display: flex;
                flex-wrap: wrap;
                justify-content: center;
                align-items: center;
                padding-top: 15px;
                padding-bottom: 15px;

                border: 1px solid rgb(240, 237, 237);
                border-radius: 5px;
                margin-top: 5px;
                cursor: pointer;
            }

            .summary .short{
                width: 40%;
                text-align: center;
                font-size: large;
            }
            .main_body{
                width: 101%;
                margin-top: 15px;
                justify-content: center;
            }

            @media (min-width: 799px){
                .main_body{
                    width:60%;
                    margin-left: 10px;
                }
            }

        </style>

        <!-- Styling for the quiz navigation-->
        <link rel='stylesheet' href='{% static "quizTest/quiz_nav.css" %}'>

        <!--JavaScript to make navigation more responsible-->
        <script src='{% static "quizTest/quiz_nav.js" %}'></script>

    </head>

    <body>
         <!--Include the navigation points and their url references here-->
         <nav id='nav'>
            <p class='nav_home'>Dashboard  </p>
            <div id='nav_house'>
                <div>
                    <p><a href='{% url "courses:home" %}'>Home</a></p>
                </div>
                {% if related_quizzes %}
                <div>
                    <!-- This is where the related quizzes are passed in-->
                    <h4> Other courses you can check</h4>
                    <br>

                    {% for related_quiz in related_quizzes %}
                        <p><a href='{% url "courses:leadership_board" related_quiz %}'>{{ related_quiz }}</a></p>
                    {% endfor %}
                

                </div>
                {% endif %}
                
                <div>
                    <h4>Header 1</h4>
                    <br>
                    <a href='#'><p>Exams</p></a>
                    <p><a href='#'>casots Link 2</a></p>
                    <p  class='active'>Performance</p>
                </div> 

                <div>
                    <h4>Header 2</h4>
                    <br>
                    <p><a href='#'>casos Link 3</a></p>
                    <p><a href='#'>casots Link 4</a></p>
                    <p><a href='#'>casots Link 5</a></p>
                    <p><a href='#'>casots Link 6</a></p>
                </div> 

                <div>
                    <h4>Header 3</h4>
                    <br>
                    <p><a href='#'>casots Link 7</a></p>
                    
                </div> 
            </div>
        </nav>

        <br>
        <div class='main_body'>
        <div id='score_container'>

                <div id='dateholder'>
                    {% if submission_date %}
                        {{ submission_date }}
                    {% endif %}
                </div>

                <div id='score'>
                    {% if score %}
                   <p>Your Score: {{ score }}%</p> 
                        
                    {% endif %}
                </div>
            

            <div id='user_course'>
                <div id='user'>
                   
                </div>

                <div id='course'>
                    {% if course %}
                        {{ course }}
                    {% endif %}
                </div>
            

            
        
        </div>

           <br>
        </div>

        <div id='history'>
            <p style='text-align: center;'><strong>User ranking for {{user_performances.0.course }}</strong> </p>
            {% if user_performances %}

            {% for performance in user_performances %}
                <div class='summary' data-score='{{ performance.score }}' data-course='{{ performance.course }}' data-date='{{ performance.date }}' data-user='{{ performance.user }}'>
                    <p class='short'>{{ performance.course }}</p>
                    <p class='short'>{{ performance.date }}</p>
                </div>
            {% endfor %}
            
            {% else %}
                <div class='summary'>
                    <p><strong>No History yet</strong></p>
                </div>
            {% endif %}

        </div>

    </div>
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            //What we want to achieve with the javascript is, on click of a previous performance, it replaces the content of the displayed performance
            //Query for all performances
            History = document.querySelectorAll('.summary')
            History.forEach(function(summary){

                //On click of each performance(summary)
                summary.onclick = function(){
                    //Change all other summaries background color to white
                    History.forEach(function(changeColor){
                        changeColor.style.backgroundColor = 'white';
                    })
                    //While you keep the current summary's color at light blue for example
                    this.style.backgroundColor = 'rgb(221, 221, 250)';

                    // This section attempts to replace the displayed performance
                        //Get the data you want to pass in
                        displayScore = this.getAttribute('data-score')
                        displayCourse = this.getAttribute('data-course')
                        displayDate = this.getAttribute('data-date')
                        displayUser = this.getAttribute('data-user')

                        //Replace the current displayed performance with the new data
                        document.querySelector('#score').innerHTML = `<p>${displayUser}'s Score: ${displayScore}%</p>`
                        document.querySelector('#user_course #course').innerHTML = `${displayCourse}`
                        document.querySelector('#user_course #user').innerHTML = `${displayUser}`
                        document.querySelector('#score_container #dateholder').innerHTML = `Date Taken: ${displayDate}`

           


                    
                }
            })
        })
    </script>
    </body>
</html>