casots/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls'))
]
urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls import url


app_name='courses'

urlpatterns = [
     
    # path('',views.home, name='home'),
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('registration/',views.register, name='registration'),
#     path('login/', views.login_view, name='login'),
    
    #new
    path('loginquiz/<slug:quiz>/', views.login_quiz, name='login_quiz'),

    path('logout/',views.logout_view, name='logout'),   
    path('courses/', views.courses_list, name='course_list' ),
    path('category/<slug:category_slug>/', views.courses_list, name='category_list_by_category'),
    path('contact-us/' ,views.contact_us, name='contact_us'),

 
    path('courses/<slug:course_slug>/',views.course_summary, name = 'course_summary'),
    
    
    # reset password
    path('reset_password/',
         auth_views.PasswordResetView.as_view(template_name='courses/registration/password_reset.html'),
         name='reset_password'),
    
    path('reset_password_sent/',
         auth_views.PasswordResetDoneView.as_view(template_name='courses/registration/password_reset_sent.html'),
         name='password_reset_done'),
    
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='courses/registration/password_reset_form.html'),
         name='password_reset_confirm'),
    
    path('reset_password_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='courses/registration/password_reset_done.html'),
         name='password_reset_complete'),
    
    
     # QUIZ SECTION
    path('quizinstructions/<str:category>/', views.quiz_instructions, name='quiz_instructions'),
 
     #trial
     path('quiz/<str:quiz>/',views.index, name='index'),

     path('quiz_performance/', views.quiz_performance, name='quiz_performance'),

      # Leadership board. For all test takers
    path('leaderboard/<str:quiz>/', views.leadership_board, name='leadership_board'),


#     path('course/<str:category>/', views.course_main, name='course_main'),
    
     
]

courses/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, get_user_model
from django.utils.translation import gettext as _

User=get_user_model()

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username and password:
                user = authenticate(username=username, password=password)
                if not user:
                    raise forms.ValidationError("This user does not exists")
                if not user.check_password(password):
                    raise forms.ValidationError("Incorrect password")
                if not user.is_active:
                    raise forms.ValidationError("This user is not active")
        return super(UserLoginForm, self).clean(*args, **kwargs)


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name= forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    
    class Meta:
        model=User
        fields =('username',
                 'email',
                 'first_name',
                 'last_name',
                 'password1',
                 'password2')
        

    def save(self,commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user_last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        
        if commit:
            user.save()
        return user
    
class ContactForm(forms.Form):
    first_name= forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email_address = forms.EmailField(max_length=150)
    message = forms.CharField(widget=forms.Textarea)

courses/views.py
from django.shortcuts import render,redirect,HttpResponse,get_object_or_404
from django.urls import reverse
from courses.models import Courses,Category
from django.core.paginator import Paginator
# from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.decorators import login_required
from .forms import RegistrationForm, UserLoginForm, ContactForm
from django.contrib.auth import login, authenticate , logout
from django.contrib import messages
from .models import QuizProfile, QuizQuestion,Quiz, Leadership_board
from django.http import Http404, HttpResponseRedirect
import datetime
from monthdelta import monthdelta
from django.core.mail import send_mail,BadHeaderError
from django.contrib.auth.decorators import login_required




#home page 

def home(request):
    context={}
    return render(request, 'courses/index.html',context)

# about page
def about(request):
    context={}
    return render(request, 'courses/about.html', context)

# all the courses page
def courses_list(request, category_slug=None):
    category =None
    courses = Courses.objects.all()
    if category_slug:
        category = Category.objects.get(slug = category_slug )
        courses =  courses.filter(category=category)
    paginator = Paginator(courses, 4)
    page_number=request.GET.get('page')
    courses = paginator.get_page(page_number)
    
    context = {'course':courses}
    return render(request, 'courses/course_list.html', context)


# summary of each course
def course_summary(request, course_slug):
    courses = Courses.objects.get(slug=course_slug)
    context = {'courses':courses}
    return render(request, 'courses/course_summary.html', context)

def contact_us(request):
    if request.method =='POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject="Website Inquiry"
            body={
                'first_name':form.cleaned_data['first_name'],
                'last_name':form.cleaned_data['last_name'],
                'email':form.cleaned_data['email_address'],
                'first_name':form.cleaned_data['message'],
            }
            message ="\n".join(body.values())
            try:
                send_mail(subject, message, 'umohu67@gmail.com', ['umohu67@gmail.com'])
            except BadHeaderError:
                return HttpResponse('invalid header found.')
            return redirect ("courses:home")
        
    form=ContactForm()
    context={'form':form}
    return render(request ,'courses/contact-us.html' , context )

# logout page
def logout_view(request):
    logout(request)
    return redirect("/login")

# register page
def register(request):
    form = RegistrationForm(request.POST)     
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('/courses')

    context = {'form': form}
    return render(request, 'courses/registration/sign_up.html', context=context)

# login page
def login_view(request):
    form =UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('/dashboard')
    return render(request, 'courses/registration/sign_in.html', {"form": form})

# QUIZ SECTION
# login page if user tries to access quiz without login
def login_quiz(request, quiz):
    form =UserLoginForm(request.POST or None)
    quiz = quiz
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        login(request, user)
        return HttpResponseRedirect(reverse('courses:course_summary', args=[quiz]))
    return render(request, 'courses/registration/sign_up.html', {"form": form})

def index(request, quiz):

    #If user not logged in
    if not request.user.is_authenticated:
        
        course = Courses.objects.filter(name=quiz).first()
        quizName = course.slug
        return HttpResponseRedirect(reverse('courses:login_quiz', args=[quizName]))

    if request.method == 'POST':
        
        #Login user as user
        user = request.user.username

        quizName = quiz
        
        get_questions = QuizQuestion.objects.filter(quiz__course__name=quizName).all()
       
        if len(get_questions)<= 0:
            return render(request, 'quizTest/error.html',{'error_msg':f"it is not your fault, it is ours. We couldn't find {quizName}"})
        
        try:
            recent = Leadership_board.objects.filter(user=user).filter(course=quizName).last()
            
            renew_access = recent.last_renewal + monthdelta(6)
            
            submission_date =datetime.date.today()
            
            get_time_difference =renew_access - submission_date
            
            time_left_before_renew = get_time_difference.days
            
            if time_left_before_renew>0:
                have_trials=False
                
                if recent.trials>10:
                    have_trials =False
                else:
                    have_trials =True
                    
            else:
                recent.last_renewal=submission_date
                recent.trials =0
                recent.save()
                have_trials = True
                
                
        except:
            have_trials = True
        
            
        if have_trials == True:
          
            get_questions = QuizQuestion.objects.filter(quiz__course__name =quizName).all()
            
            if len(get_questions)>0:
                questionSet=[]
                index = 0
                for question in get_questions:
                    
                    quest = question.question
                    
                    
                    
                    try:
                        
                        
                        questionSet.append({
                            'index': index,
                            'question':quest,
                            'A': question.A,
                            'B': question.B,
                            'C': question.C,
                            'D': question.D,
                            'answer': question.correct_answer,
                        })
                    except:
                        answer = 'None'
                        
                        questionSet.append({
                            'question':quest,
                            'A':'None',
                            'B':'None',
                            'C':'None',
                            'D':'None',
                            
                            'answer':answer
                        })

                    index += 1
                try:
                    course_name = Courses.objects.filter(slug=quizName).first()
                    
                    
                    course_category = course_name.category.name       
                    related_quiz = Quiz.objects.filter(course__category__name=course_category).all()
                    listit = list(related_quiz)
                except:
                    listit = []
                related_quizzes=[]
                
                for i in listit:
                    if i.course.slug == quizName:
                        pass
                    else:
                        related_quizzes.append(i.course.slug)
                        
                quiz_duration =Quiz.objects.filter(course__slug=quizName).first()
                
                try:
                    duration =quiz_duration.duration
                    time_denotation = quiz_duration.time_denotation
                    
                except:
                    duration =30
                    time_denotation ='min'
                    
                context={
                    'questionSet':questionSet,
                    'course':quizName,
                    'user': user,
                    'related_quizzes':related_quizzes,
                    'duration':duration,
                    'time_denotation': time_denotation,
                }
                return render(request, 'quizTest/quiz.html', context)
            else:
                if len(get_questions) <1:
                    return HttpResponse('Error no existing question')
        else:
            return render(request, 'quizTest/error.html',{'error_msg': f'You have used up your trials for {quizName}', 'extra_info': f'Course accessible from {renew_access}'})
                
    else:
        return render(request, 'quizTest/error.html', {'error_msg': f' Wrong turn, it seems you attempted to access this page from the wrong point'})





# def course_main(request, category):
#     category=str(category)
    
#     category =Category.objects.filter(name=category).all()
    
#     try:
#         course_category =category[0].name
#         related_courses =courses.objects.filter(category__name = course_category).all()
        
#         try:
#             listit =list(related_courses)
            
#             return render(request, 'quizTest/course.html',{'related_courses': listit})
#         except:
#             return HttpResponse('No course yet')
#     except:
#         return HttpResponse('Nothing here yet')



# function that handles quiz details.
def quiz_instructions(request, category):
    course = str(category)
    
    #quizName = Quiz.objects.filter(course__slug__icontains = course).all()
    quizName = Quiz.objects.filter(course__slug = course).all()
    
    context={
        'quizName':quizName
    }
    return render(request,'quizTest/quiz_details.html', context)

# def Leadership_board(request, quiz):

templates/courses/course_summary.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- description -->
    <section class="description">
        <div class="container">
            <div class="flex d-flex justify-content-around flex-wrap">
                <div class="summary">
                  <h2>{{courses.name}}</h2>
                    <div class="top d-flex justify-content-around">
                        <div class="review">
                            <h3>Review</h3>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                            <i class="fa fa-star" aria-hidden="true"></i>
                           
                        </div>
                        <div class="">
                            <hr class="vertical">
                        </div>
                        <div class="category-heading">
                            <h3>Category</h3>
                            <h5>{{courses.category.name}}</h5>
                        </div>
                    </div>

                    <div class="course-description mt-3">
                        <img class="card-img-top" src="{{courses.images.url}}" alt="Card image cap">
                        <div class="columns">
                            <div class="mt-5 d-flex ">
                            <div class="list-group list-group-horizontal" id="list-tab" role="tablist">
                                <a class="list-group-item list-group-item-action active activity  mr-2" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">Description</a>
                            </div>
                            </div>
                            <div class="border p-4">
                            <div class="tab-content" id="nav-tabContent">
                                <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">{{courses.description | safe}}</div>
                            </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="category">
                    <ul class="nav flex-column list">
                        <li class="nav-item dropdown group">
                          <a class="nav-link color p-3" href="#" role="button" data-toggle="dropdown"><i class="fa fa-angle-down down" aria-hidden="true"></i> Art and Design</a>
                          <div class="dropdown-menu col-md-12" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">Action</a>
                            <a class="dropdown-item" href="#">Another action</a>
                        </li>
                        
                        <li class="nav-item dropdown group">
                            <a class="nav-link p-3 color" href="#" role="button" data-toggle="dropdown"><i class="fa fa-angle-down down" aria-hidden="true"></i> Business</a>
                            <div class="dropdown-menu col-md-12" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="#">Accounting</a>
                              <a class="dropdown-item" href="#">MAss COmmunication</a>
                          </li>
              

                          <li class="nav-item dropdown group">
                            <a class="nav-link p-3 color" href="#" role="button" data-toggle="dropdown"><i class="fa fa-angle-down down" aria-hidden="true"></i> IT & Software</a>
                            <div class="dropdown-menu col-md-12" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="#">Android</a>
                              <a class="dropdown-item" href="#">Hacking</a>
                          </li>
                          

                          <li class="nav-item dropdown group">
                            <a class="nav-link p-3 color" href="#" role="button" data-toggle="dropdown"><i class="fa fa-angle-down down" aria-hidden="true"></i> Language</a>
                            <div class="dropdown-menu col-md-12" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="#">Action</a>
                              <a class="dropdown-item" href="#">Another action</a>
                          </li>
                    
                          <li class="nav-item dropdown group">
                            <a class="nav-link p-3 color" href="#" role="button" data-toggle="dropdown"> <i class="fa fa-angle-down down" aria-hidden="true"></i> Programming</a>
                            <div class="dropdown-menu col-md-12" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="#">Action</a>
                              <a class="dropdown-item" href="#">Another action</a>
                          </li>
                      </ul>
                      
                      <div class="take-a-quiz p-3">
                          <h2 class="take-a-quiz-heading">Take a Quiz</h2>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Sequi, unde!</p>
                        <div class="text-center">
                      
                            <!--New add on-->
                      <a href="{% url 'courses:quiz_instructions' courses.slug %}" class="btn btn-primary col-md-8 p-2 take-a-quiz-btn">Take {{ courses.name }} quiz</a>
                      <br>
                      <br>
                      <a href="{% url 'courses:leadership_board' courses.slug %}" class="btn btn-primary col-md-8 p-2 take-a-quiz-btn">Leaderboard</a>
                        </div>
    
                    </div>
                </div>

            </div>
        </div>
    </section>
    <!-- ending description -->

{% endblock content %}

templates/courses/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- hero-section -->
<section class="hero">
  <div class="container">
      <div class="hero-body text-center pt-5">
          <div class="hero-head">
              <h3>BEST ONLINE EDUCATION IN THE WORLD</h3>
              <h1>ONE STEP AHEAD THIS SEASON</h1>
              <div class="hero-links mt-4">
                  <a href="" class="learn-more">Learn More</a>
                  <a href="{% url 'courses:course_list' %}" class="view-course">view Courses</a>
              </div>
          </div>
      </div>
  </div>
</section>
<!-- hero ending -->

<!-- awesome features -->
  <section class="awesome-features mt-5">
      <div class="container">
          <div class="awesome-feature-body">
              <div class="awesome-features-heading text-center">
                  <h1>Awesome Features</h1>
                  <p class="unique3">Replenish man have thing gathering lights yielding shall you</p>
              </div>
              <div class="features d-flex flex-row justify-content-around flex-wrap mt-5">
                  <div class="card " style="width: 23rem;">
                     <i class="fa fa-cogs text-center unique2"style="font-size: 4em" aria-hidden="true"></i>
                      <div class="card-body">
                        <h1 class="card-title text-center">The Experts</h1>
                        <p class="card-text text-center">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Molestiae quos sed quae nesciunt provident quasi rerum ex ullam laboriosam deserunt magnam laborum excepturi accusamus, ipsum explicabo, labore consequuntur molestias vitae est. Ducimus voluptates perspiciatis, omnis vel suscipit quibusdam dolorum. Aliquid iure in nulla eum magnam quam ad?</p>
                      </div>
                  </div>

                  <div class="card" style="width: 23rem;">
                      <i class="fas fa-code text-center unique2" style="font-size: 4em"></i>
                      <div class="card-body">
                         <h1 class="card-title text-center">Best Courses</h1>
                         <p class="card-text text-center">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Molestiae quos sed quae nesciunt provident quasi rerum ex ullam laboriosam deserunt magnam laborum excepturi accusamus, ipsum explicabo, labore consequuntur molestias vitae est. Ducimus voluptates perspiciatis, omnis vel suscipit quibusdam dolorum. Aliquid iure in nulla eum magnam quam ad?</p>
                       </div>
                   </div>

                   <div class="card" style="width: 23rem;">
                      <i class="fas fa-award text-center unique2" style="font-size: 4em"></i>
                       <div class="card-body">
                         <h1 class="card-title text-center">Award & Reward</h1>
                         <p class="card-text text-center">Lorem ipsum, dolor sit amet consectetur adipisicing elit. Molestiae quos sed quae nesciunt provident quasi rerum ex ullam laboriosam deserunt magnam laborum excepturi accusamus, ipsum explicabo, labore consequuntur molestias vitae est. Ducimus voluptates perspiciatis, omnis vel suscipit quibusdam dolorum. Aliquid iure in nulla eum magnam quam ad?</p>
                       </div>
                   </div>
              </div>
          </div>
      </div>
  </section>
<!-- ending awesome features -->


<!-- our popular Courses -->
<section class="our-popular-courses mt-5">
  <div class="container">
      <div class="our-popular-courses-heading text-center">
          <h1>Our Popular Courses</h1>
          <p class="unique3">Replenish man have thing gathering lights yielding shall you</p>
      </div>

      <div class="Courses d-flex flex-row justify-content-around flex-wrap mt-5">
          <div class="card shadow-lg" style="width: 22rem;">
              <img src="{% static 'images/clement-h-95YRwf6CNw8-unsplash.jpg' %}" class="card-img-top" alt="...">
              <div class="card-body ">
                <h3 class="card-title unique4">Computer Science</h3>
                <p class="card-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit corrupti nulla soluta ipsa officia debitis fugit iure inventore maiores! Corporis sed doloremque nesciunt aliquam, libero hic est dicta ex veritatis accusamus tempora in voluptate quam? Dignissimos modi amet rem illo eum aliquam quod officia. Suscipit voluptatibus ducimus adipisci assumenda!</p>
                <!-- <a href="#" class="btn btn-primary">View Courses</a> -->
              </div>
            </div>
            <div class="card shadow-lg" style="width: 22rem;">
              <img src="{% static 'images/xps-2L-0vnCnzcU-unsplash.jpg' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <h3 class="card-title unique4">Computer Engineering</h3>
                <p class="card-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Explicabo commodi eum quam! Minus nesciunt repellat magni tenetur vero, placeat quas quia labore tempore quis nostrum esse vel mollitia in expedita ut velit harum sapiente quasi. Iure veniam numquam, alias exercitationem quae eveniet nostrum suscipit perferendis libero recusandae, laboriosam velit!</p>
                <!-- <a href="#" class="btn btn-primary">View Courses</a> -->
              </div>
            </div>
            <div class="card shadow-lg" style="width: 22rem;">
              <img src="{% static 'images/mikael-kristenson-3aVlWP-7bg8-unsplash.jpg' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <h3 class="card-title unique4">Mass Communication</h3>
                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime, beatae natus. Consequuntur eius dolorem incidunt veritatis, cum voluptatem non quasi nobis ducimus vel repellendus itaque laborum explicabo accusamus alias beatae minima animi ratione dolores magni? Esse sapiente doloremque culpa rerum, quidem pariatur optio. Porro officia sequi nemo quam provident!</p>
                <!-- <a href="#" class="btn btn-primary">View Courses</a> -->
              </div>
            </div>

      </div>
  </div>
</section>
<!-- ending our popular Courses -->


<!--register Now  -->
<section class="register-now mt-5">
 <div class="container ">
    <div class="registration p-5">
        <div class="register mt-5 text-center">
          <h1>Register Now</h1>
          <p>this is a moment in the life of any aspiring astronomer that is time to buy that first telescope. it's exiting to think about setting up your own viewing station</p>
          <div class="hero-links mt-4">
            <a href="{% url 'courses:registration' %}" class="view-course ">Register</a>
        </div>
    </div>     
 </div>
</section>

<!--ending register Now  -->


<!-- Clients Says About Us -->
<!-- <section class="clients-says-about-us mt-5">
 <div class="container text-center">
   <div class="client-review">
     <h1>Clients Says About Us</h1>
     <p>replenish man have thing gathering lights yielding shall you</p> -->
     <!-- carousel -->
     <!-- <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
  
      <div class="carousel-inner">
        <div class="carousel-item unique text-center mt-5 active">
          <p>ccusamus, nem, ex accusamus deserunt reiciendis magni animi atque. Modi inventore veniam, corrupti iste laudantium suscipit a placeat aut numquam! Enim voluptatem amet quaerat harum cupiditate sed ipsam vero eligendi odit, at, sit deserunt. Ipsum fuga rem porro natus!</p>
         <div class="proile-flex text-center">
            <img src="asset/images/800.jpg" class="round" alt="">
            <span class="unique5 ml-3">
              <h3>udonwa</h3>
              <p>new york city</p>
            </span>
         </div>
      </div>
        
        <div class="carousel-item unique text-center mt-5 ">
          <p>ccusamus, nem, ex accusamus deserunt reiciendis magni animi atque. Modi inventore veniam, corrupti iste laudantium suscipit a placeat aut numquam! Enim voluptatem amet quaerat harum cupiditate sed ipsam vero eligendi odit, at, sit deserunt. Ipsum fuga rem porro natus!</p>
         <div class="proile-flex text-center">
            <img src="asset/images/800.jpg" class="round" alt="">
            <span class="unique5 ml-3">
              <h3>udonwa</h3>
              <p>new york city</p>
            </span>
         </div>
      </div>

        <div class="carousel-item unique text-center mt-5 ">
          <p>ccusamus, nem, ex accusamus deserunt reiciendis magni animi atque. Modi inventore veniam, corrupti iste laudantium suscipit a placeat aut numquam! Enim voluptatem amet quaerat harum cupiditate sed ipsam vero eligendi odit, at, sit deserunt. Ipsum fuga rem porro natus!</p>
         <div class="proile-flex text-center">
            <img src="asset/images/800.jpg" class="round" alt="">
            <span class="unique5 ml-3">
              <h3>udonwa</h3>
              <p>new york city</p>
            </span>
         </div>
      </div>

      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon color" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div> -->

     <!--ending carousel  -->
   <!-- </div>
 </div>
</section> -->
<!-- ending Clients Says About Us -->


{% endblock content %}